# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cd4885657d7b7fe5361c4a6a6851b551dd4d93825d404f3b5566b09cff4dfb2c2533c29450d943c1ddb4fb96626d1135e009ccb08cecefaa234881d5676c9142

test:
  secret_key_base: 66b9e0b34178c26d2ca2d5688647c136082adb65339aa7d6574c54dfaf861ab37083c6e1761d6f3c659f6f9e149f6e207834e80f2d7f833eec6abca42874a1be

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
